#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/interface
#
# IDENTIFICATION
#    src/backend/access/interface/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/interface
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	ifamapi.o ordering.o hashing.o

include $(top_srcdir)/src/backend/common.mk
